# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/chan/Desktop/StaticScript-master-2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/chan/Desktop/StaticScript-master-2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.29.3/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chan/Desktop/StaticScript-master-2/CMakeFiles /Users/chan/Desktop/StaticScript-master-2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/chan/Desktop/StaticScript-master-2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named intrinsics_gen

# Build rule for target.
intrinsics_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 intrinsics_gen
.PHONY : intrinsics_gen

# fast build rule for target.
intrinsics_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/intrinsics_gen.dir/build.make CMakeFiles/intrinsics_gen.dir/build
.PHONY : intrinsics_gen/fast

#=============================================================================
# Target rules for targets named omp_gen

# Build rule for target.
omp_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 omp_gen
.PHONY : omp_gen

# fast build rule for target.
omp_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/omp_gen.dir/build.make CMakeFiles/omp_gen.dir/build
.PHONY : omp_gen/fast

#=============================================================================
# Target rules for targets named acc_gen

# Build rule for target.
acc_gen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 acc_gen
.PHONY : acc_gen

# fast build rule for target.
acc_gen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/acc_gen.dir/build.make CMakeFiles/acc_gen.dir/build
.PHONY : acc_gen/fast

#=============================================================================
# Target rules for targets named staticscript

# Build rule for target.
staticscript: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 staticscript
.PHONY : staticscript

# fast build rule for target.
staticscript/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/staticscript.dir/build.make CMakeFiles/staticscript.dir/build
.PHONY : staticscript/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) $(MAKESILENT) -f lib/CMakeFiles/lib.dir/build.make lib/CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named entity

# Build rule for target.
entity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 entity
.PHONY : entity

# fast build rule for target.
entity/fast:
	$(MAKE) $(MAKESILENT) -f src/Entity/CMakeFiles/entity.dir/build.make src/Entity/CMakeFiles/entity.dir/build
.PHONY : entity/fast

#=============================================================================
# Target rules for targets named ast

# Build rule for target.
ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ast
.PHONY : ast

# fast build rule for target.
ast/fast:
	$(MAKE) $(MAKESILENT) -f src/AST/CMakeFiles/ast.dir/build.make src/AST/CMakeFiles/ast.dir/build
.PHONY : ast/fast

#=============================================================================
# Target rules for targets named sema

# Build rule for target.
sema: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sema
.PHONY : sema

# fast build rule for target.
sema/fast:
	$(MAKE) $(MAKESILENT) -f src/Sema/CMakeFiles/sema.dir/build.make src/Sema/CMakeFiles/sema.dir/build
.PHONY : sema/fast

#=============================================================================
# Target rules for targets named codegen

# Build rule for target.
codegen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
.PHONY : codegen

# fast build rule for target.
codegen/fast:
	$(MAKE) $(MAKESILENT) -f src/CodeGen/CMakeFiles/codegen.dir/build.make src/CodeGen/CMakeFiles/codegen.dir/build
.PHONY : codegen/fast

#=============================================================================
# Target rules for targets named optimization

# Build rule for target.
optimization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 optimization
.PHONY : optimization

# fast build rule for target.
optimization/fast:
	$(MAKE) $(MAKESILENT) -f src/Optimization/CMakeFiles/optimization.dir/build.make src/Optimization/CMakeFiles/optimization.dir/build
.PHONY : optimization/fast

#=============================================================================
# Target rules for targets named driver

# Build rule for target.
driver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 driver
.PHONY : driver

# fast build rule for target.
driver/fast:
	$(MAKE) $(MAKESILENT) -f src/Driver/CMakeFiles/driver.dir/build.make src/Driver/CMakeFiles/driver.dir/build
.PHONY : driver/fast

antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.o: antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.o
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.o

# target to build an object file
antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.o
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.o

antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.i: antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.i
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.i

# target to preprocess a source file
antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.i
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.i

antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.s: antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.s
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.s

# target to generate assembly for a file
antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.s
.PHONY : antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.cpp.s

antlr4_generated_src/StaticScriptParser/StaticScriptParser.o: antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.o

# target to build an object file
antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.o

antlr4_generated_src/StaticScriptParser/StaticScriptParser.i: antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.i

# target to preprocess a source file
antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.i

antlr4_generated_src/StaticScriptParser/StaticScriptParser.s: antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.s

# target to generate assembly for a file
antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParser.cpp.s

antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.o: antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.o

# target to build an object file
antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.o

antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.i: antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.i

# target to preprocess a source file
antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.i

antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.s: antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.s

# target to generate assembly for a file
antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.cpp.s

antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.o: antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.o

# target to build an object file
antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.o
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.o

antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.i: antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.i

# target to preprocess a source file
antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.i
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.i

antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.s: antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.s

# target to generate assembly for a file
antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/parser.dir/build.make CMakeFiles/parser.dir/antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.s
.PHONY : antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... acc_gen"
	@echo "... intrinsics_gen"
	@echo "... lib"
	@echo "... omp_gen"
	@echo "... ast"
	@echo "... codegen"
	@echo "... driver"
	@echo "... entity"
	@echo "... optimization"
	@echo "... parser"
	@echo "... sema"
	@echo "... staticscript"
	@echo "... antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.o"
	@echo "... antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.i"
	@echo "... antlr4_generated_src/StaticScriptLexer/StaticScriptLexer.s"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParser.o"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParser.i"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParser.s"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.o"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.i"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserBaseVisitor.s"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.o"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.i"
	@echo "... antlr4_generated_src/StaticScriptParser/StaticScriptParserVisitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

